# TCL File Generated by Component Editor 15.1
# Fri Apr 14 23:02:15 EDT 2023
# DO NOT MODIFY


# 
# qsys_lab_custom_component "custom_component" v1.0
# Qin Xuan Xu and William Zhang 2023.04.14.23:02:15
# qsys lab custom component
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module qsys_lab_custom_component
# 
set_module_property DESCRIPTION "qsys lab custom component"
set_module_property NAME qsys_lab_custom_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Qin Xuan Xu and William Zhang"
set_module_property DISPLAY_NAME custom_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL qsys_lab_custom_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file qsys_lab_custom_component.vhd VHDL PATH qsys_lab_custom_component.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock_sink
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset resetn reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset clock_reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 address address Input 8
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point segment0
# 
add_interface segment0 conduit end
set_interface_property segment0 associatedClock clock_sink
set_interface_property segment0 associatedReset clock_reset
set_interface_property segment0 ENABLED true
set_interface_property segment0 EXPORT_OF ""
set_interface_property segment0 PORT_NAME_MAP ""
set_interface_property segment0 CMSIS_SVD_VARIABLES ""
set_interface_property segment0 SVD_ADDRESS_GROUP ""

add_interface_port segment0 segments1 conduit Output 7


# 
# connection point segment1
# 
add_interface segment1 conduit end
set_interface_property segment1 associatedClock clock_sink
set_interface_property segment1 associatedReset clock_reset
set_interface_property segment1 ENABLED true
set_interface_property segment1 EXPORT_OF ""
set_interface_property segment1 PORT_NAME_MAP ""
set_interface_property segment1 CMSIS_SVD_VARIABLES ""
set_interface_property segment1 SVD_ADDRESS_GROUP ""

add_interface_port segment1 segments2 conduit Output 7


# 
# connection point segment2
# 
add_interface segment2 conduit end
set_interface_property segment2 associatedClock clock_sink
set_interface_property segment2 associatedReset clock_reset
set_interface_property segment2 ENABLED true
set_interface_property segment2 EXPORT_OF ""
set_interface_property segment2 PORT_NAME_MAP ""
set_interface_property segment2 CMSIS_SVD_VARIABLES ""
set_interface_property segment2 SVD_ADDRESS_GROUP ""

add_interface_port segment2 segments3 conduit Output 7


# 
# connection point segment3
# 
add_interface segment3 conduit end
set_interface_property segment3 associatedClock clock_sink
set_interface_property segment3 associatedReset clock_reset
set_interface_property segment3 ENABLED true
set_interface_property segment3 EXPORT_OF ""
set_interface_property segment3 PORT_NAME_MAP ""
set_interface_property segment3 CMSIS_SVD_VARIABLES ""
set_interface_property segment3 SVD_ADDRESS_GROUP ""

add_interface_port segment3 segments4 conduit Output 7

